version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.backend.dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"


  frontend:
    build:
        context: .
        dockerfile: Dockerfiles/Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
