# Generated by Django 4.2.6 on 2023-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="blog_post_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
