# Generated by Django 4.2.6 on 2023-11-13 17:40

import blog.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpostpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock()),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("alt", wagtail.blocks.CharBlock(require=False)),
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h3",
                                            "bold",
                                            "italic",
                                            "link",
                                            "code",
                                        ]
                                    ),
                                )
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "images",
                        wagtail.blocks.ListBlock(
                            blog.models.ImageBlock, required=False
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
