# Generated by Django 4.2.6 on 2023-12-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpostpage_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='blog_post_title',
        ),
    ]
