# Generated by Django 4.2.6 on 2023-11-08 11:58

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_receipepostpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="images",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                default=0,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
