# Generated by Django 4.2.6 on 2023-11-08 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blogpostpage_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostpage",
            name="images",
        ),
    ]
