# Generated by Django 4.2.6 on 2023-11-08 15:34

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_blogpostpage_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="images",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
