# Generated by Django 4.2.6 on 2023-11-08 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_blogpostpage_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipepostpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
        migrations.DeleteModel(
            name="ReceipePostPage",
        ),
    ]
