
FROM	python:3.8.1-slim-buster
ENV	PYTHONUNBUFFERED	1
WORKDIR	/app
RUN	apt-get update --yes --quiet \
	&& apt-get install -y \
	build-essential \
	libpq-dev \
	libmariadbclient-dev \
	libjpeg62-turbo-dev \
	zlib1g-dev \
	libwebp-dev \
	&& rm -rf /var/lib/apt/lists/*
COPY	backend/requirements.txt	/app/
RUN	pip install --no-cache-dir -r requirements.txt
COPY	backend	/app/
RUN	python manage.py collectstatic --noinput --clear
EXPOSE	8000
CMD	["python","manage.py","runserver","0.0.0.0:8000"]
