# Generated by Django 4.1.7 on 2023-02-21 17:53

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tittel')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='publisert')),
                ('drawing', models.ImageField(upload_to='drawing', verbose_name='Tegning')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'db_table': 'drawing',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='tittel')),
                ('description', tinymce.models.HTMLField(verbose_name='beskrivelse')),
                ('created_date', models.DateField(default=django.utils.timezone.now, verbose_name='opprettet')),
                ('updated_date', models.DateField(default=django.utils.timezone.now, verbose_name='oppdatert')),
                ('state', models.CharField(choices=[('SKETCHED', 'På tapetet'), ('TODO', 'På bordet'), ('HOLD', 'I skuffen'), ('DONE', 'I arkivet')], default='IDEA', max_length=30, verbose_name='tilstand')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logos/')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['updated_date'],
            },
        ),
    ]
