# Generated by Django 4.1.7 on 2023-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simzam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
