# Generated by Django 4.1.7 on 2023-03-20 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simzam', '0002_drawing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='slug',
        ),
        migrations.AddField(
            model_name='drawing',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='tittel'),
        ),
    ]
