# Generated by Django 4.1.6 on 2023-06-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simzam', '0006_alter_project_state_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('SKETCHED', 'På tapetet'), ('TODO', 'På bordet'), ('HOLD', 'I skuffen'), ('DONE', 'I arkivet')], default='IDEA', max_length=30, verbose_name='tilstand'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
